"""add structured frequency fields to routine

Revision ID: 86cabfc911b6
Revises: 96d03b9e8a9b
Create Date: 2025-07-07 12:11:31.958199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86cabfc911b6'
down_revision: Union[str, Sequence[str], None] = '96d03b9e8a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routine', sa.Column('frequency_type', sa.String(), nullable=True))
    op.add_column('routine', sa.Column('frequency_days', sa.String(), nullable=True))
    op.add_column('routine', sa.Column('frequency_count', sa.Integer(), nullable=True))
    op.add_column('routine', sa.Column('frequency_custom', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routine', 'frequency_custom')
    op.drop_column('routine', 'frequency_count')
    op.drop_column('routine', 'frequency_days')
    op.drop_column('routine', 'frequency_type')
    # ### end Alembic commands ###
